version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MARIADB_DB
        - MARIADB_USER
        - MARIADB_PASS
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure    

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/agoujdam/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/agoujdam/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge